export class Product {
  productid: number;
  productcode: string;
  productname: string;
  spec: string;
  materials: string;
  unit: string;
  packunit: string;
  packqty: number;
  m3: number;
  length: number;
  width: number;
  height: number;
  remark1: string;
  remark2: string;
  remark3: string;
  remark4: string;
  remark5: string;
  remark6: string;
  remark7: string;
  remark8: string;
  remark9: string;
  remark10: string;
  useflag: number;
  level1review: number;
  level1name: string;
  level1date: Date;
  level2review: number;
  level2name: string;
  level2date: Date;
  creater: string;
  createdAt: Date;
  updater: string;
  updatedAt: Date;
  productareaid: number;
  warehouseid: number;
  del_uuid:number;
  deletedAt:Date;
  deleter:string;
}