export interface IClient {
  clientid: number;
  clientcode: string;
  clientname: string;
  contactperson: string;
  salesman: string;
  ymrep: string;
  phone_no: string;
  tel_no: string;
  email: string;
  address: string;
  discount: number;
  moneytype: string;
  useflag: number;
  level1review: number;
  level1name: string;
  level1date: Date;
  level2review: number;
  level2name: string;
  level2date: Date;
  remark1: string;
  remark2: string;
  remark3: string;
  remark4: string;
  remark5: string;
  remark6: string;
  remark7: string;
  remark8: string;
  remark9: string;
  remark10: string;
  creater: string;
  createdAt: Date;
  updater: string;
  updatedAt: Date;
  clientareaid: number;
  operateareaid: number;
  currencyid: number;
  del_uuid:number;
  deletedAt:Date;
  deleter:string;
  gs:number;
}